//@Error Handler
export const SUCCESS_MSG='SUCCESS_MSG';
export const ERROR_MSG='ERROR_MSG';
export const CLEAR_MSG='CLEAR_MSG';

//@SignIn
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

//@SignUp
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

//@LoadExisting Data
export const LOAD_MANAGE_DATA = 'LOAD_MANAGE_DATA';
export const LOAD_FORM_DATA='LOAD_FORM_DATA';

//@Home
export const HOME_DATA_START='HOME_DATA_START';
export const HOME_PROJECT_DATA_SUCCESS='HOME_PROJECT_DATA_SUCCESS';
export const HOME_PROJECT_DATA_FAIL='HOME_PROJECT_DATA_FAIL';
export const HOME_MYPROJECT_DATA_SUCCESS='HOME_MYPROJECT_DATA_SUCCESS';
export const HOME_MYPROJECT_DATA_FAIL='HOME_MYPROJECT_DATA_FAIL';
export const HOME_USER_DATA_SUCCESS='HOME_USER_DATA_SUCCESS';
export const HOME_USER_DATA_FAIL='HOME_USER_DATA_FAIL';